import test from 'node:test';
import assert from 'node:assert/strict';
import {Worker} from 'node:worker_threads';
import {demoData,backtest} from '../dist/engine.mjs';
import {parseValues,buildGrid,splitBars,evaluate,rank} from '../dist/optimizer.mjs';
const base={strategy:'cross',capital:10000,size:95,fee:.1,slippage:.05,fast:20,slow:50,rsiPeriod:14,oversold:30,overbought:70,stop:3,take:6,entry:{left:'close',right:'number',value:50000,op:'above'},exit:{left:'close',right:'number',value:50000,op:'below'}};
test('ranges are inclusive, decimal-safe and deduplicated',()=>{assert.deepEqual(parseValues('0.1:0.3:0.1,0.2',1),[.1,.2,.3]);assert.deepEqual(parseValues('',7),[7]);assert.throws(()=>parseValues('1:3:0',1));assert.throws(()=>parseValues('1,,2',1));assert.throws(()=>parseValues('1:1000:1',1));});
test('family grids avoid irrelevant cross multiplication and skip incompatible averages',()=>{const g=buildGrid(base,{families:['cross','rsi'],ranges:{fast:'10,60',slow:'40,50',rsiPeriod:'7,14',oversold:'20,30',stop:'2,3',take:'4,6'}});assert.equal(g.configs.filter(c=>c.strategy==='cross').length,8);assert.equal(g.configs.filter(c=>c.strategy==='rsi').length,16);assert.equal(g.skipped,8);assert.ok(g.configs.every(c=>c.fast<c.slow));});
test('custom rule numeric thresholds are actually varied',()=>{const g=buildGrid({...base,strategy:'custom'},{families:['custom'],ranges:{entryValue:'40000,50000',exitValue:'30000,35000'}});assert.equal(g.configs.length,4);assert.deepEqual(g.configs.map(c=>[c.entry.value,c.exit.value]),[[40000,30000],[40000,35000],[50000,30000],[50000,35000]]);assert.equal(base.entry.value,50000);});
test('search limit and invalid parameters fail before execution',()=>{assert.throws(()=>buildGrid(base,{families:['cross'],ranges:{fast:'2:100:1',slow:'101:200:1',stop:'1,2'}}),/10,000/);assert.throws(()=>buildGrid(base,{families:['cross'],ranges:{stop:'-1'}}));});
test('holdout is disjoint; summary matches standalone backtests in each segment',()=>{const data=demoData(300),s=splitBars(data,20);assert.equal(s.train.length,240);assert.equal(s.holdout.length,60);assert.ok(s.train.at(-1).time<s.holdout[0].time);const row=evaluate(base,s,0);assert.equal(row.train.netPct,backtest(s.train,base).netPct);assert.equal(row.holdout.netPct,backtest(s.holdout,base).netPct);assert.throws(()=>splitBars(demoData(50),20));});
test('ranking uses training only, honors minimum trades and handles infinity',()=>{const rows=[{id:0,train:{trades:5,netPct:20,maxDD:8,profitFactor:Infinity},holdout:{netPct:-50}},{id:1,train:{trades:4,netPct:10,maxDD:2,profitFactor:2},holdout:{netPct:100}},{id:2,train:{trades:1,netPct:90,maxDD:1,profitFactor:Infinity}}];assert.deepEqual(rank(rows,'netPct',3).map(r=>r.id),[0,1]);assert.deepEqual(rank(rows,'maxDD',3).map(r=>r.id),[1,0]);assert.deepEqual(rank(rows,'profitFactor',3).map(r=>r.id),[0,1]);});
test('real background worker finishes all candidates and returns matching metrics',async()=>{
 const url=new URL('../dist/optimizer-worker.mjs',import.meta.url).href;
 const shim=`const {parentPort}=require('node:worker_threads');global.self={postMessage:v=>parentPort.postMessage(v)};import(${JSON.stringify(url)}).then(()=>parentPort.on('message',data=>self.onmessage({data})));`;
 const worker=new Worker(shim,{eval:true}),bars=demoData(200),spec={families:['cross','rsi'],ranges:{stop:'2,3',take:'4,6'},holdout:20};
 try{const rows=await new Promise((resolve,reject)=>{const all=[];worker.on('error',reject);worker.on('message',m=>{if(m.type==='batch')all.push(...m.rows);if(m.type==='error')reject(Error(m.message));if(m.type==='done')resolve(all);});worker.postMessage({bars,base,spec});});assert.equal(rows.length,8);assert.equal(rows[0].train.netPct,backtest(splitBars(bars,20).train,rows[0].config).netPct);}finally{await worker.terminate();}
});
