# Generated by Django 5.2.17 on 2026-09-11 13:01

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Heartbeat',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(default='starting', max_length=20)),
                ('detail', models.CharField(blank=True, max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='LoginThrottle',
            fields=[
                ('key', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('window_start', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Candle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=20)),
                ('interval', models.CharField(default='1m', max_length=5)),
                ('opened_at', models.DateTimeField()),
                ('closed_at', models.DateTimeField()),
                ('fetched_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('payload', models.JSONField()),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('symbol', 'interval', 'opened_at'), name='candle_unique')],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=30)),
                ('source_id', models.CharField(max_length=160)),
                ('symbol', models.CharField(max_length=20)),
                ('kind', models.CharField(max_length=20)),
                ('event_at', models.DateTimeField()),
                ('received_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('available_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('payload', models.JSONField()),
            ],
            options={
                'indexes': [models.Index(fields=['symbol', 'id'], name='trading_eve_symbol_069faf_idx'), models.Index(fields=['symbol', 'kind', 'received_at'], name='trading_eve_symbol_9b1318_idx')],
                'constraints': [models.UniqueConstraint(fields=('source', 'source_id', 'symbol', 'kind'), name='event_source_unique')],
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(max_length=20)),
                ('params', models.JSONField(default=dict)),
                ('status', models.CharField(default='queued', max_length=20)),
                ('result', models.JSONField(default=dict)),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('started_at', models.DateTimeField(null=True)),
                ('finished_at', models.DateTimeField(null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Run',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('symbol', models.CharField(max_length=20)),
                ('mode', models.CharField(max_length=15)),
                ('status', models.CharField(default='running', max_length=20)),
                ('config', models.JSONField()),
                ('config_hash', models.CharField(max_length=64)),
                ('state', models.JSONField(default=dict)),
                ('results', models.JSONField(default=dict)),
                ('last_event_id', models.BigIntegerField(default=0)),
                ('entries_paused', models.BooleanField(default=False)),
                ('flatten_requested', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ended_at', models.DateTimeField(null=True)),
                ('error', models.TextField(blank=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('validation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='trading.run')),
            ],
        ),
        migrations.CreateModel(
            name='LiveOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('client_id', models.CharField(max_length=36, unique=True)),
                ('kind', models.CharField(max_length=10)),
                ('status', models.CharField(default='prepared', max_length=20)),
                ('request', models.JSONField()),
                ('response', models.JSONField(default=dict)),
                ('error', models.CharField(blank=True, max_length=300)),
                ('accounted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='trading.run')),
            ],
        ),
        migrations.CreateModel(
            name='Fill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strategy', models.CharField(max_length=20)),
                ('at', models.DateTimeField()),
                ('side', models.CharField(max_length=5)),
                ('quantity', models.DecimalField(decimal_places=16, max_digits=36)),
                ('price', models.DecimalField(decimal_places=16, max_digits=36)),
                ('fee', models.DecimalField(decimal_places=16, max_digits=36)),
                ('pnl', models.DecimalField(decimal_places=16, max_digits=36, null=True)),
                ('reason', models.TextField()),
                ('details', models.JSONField(default=dict)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fills', to='trading.run')),
            ],
        ),
        migrations.CreateModel(
            name='Decision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strategy', models.CharField(max_length=20)),
                ('event_id', models.BigIntegerField()),
                ('at', models.DateTimeField()),
                ('action', models.CharField(max_length=10)),
                ('reason', models.TextField()),
                ('features', models.JSONField()),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decisions', to='trading.run')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('run', 'strategy', 'event_id'), name='decision_once')],
            },
        ),
    ]
