# Generated by Django 5.2.17 on 2026-09-11 17:13

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0002_marketmodel_alter_job_owner_run_market_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutoCycle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(db_index=True, default='queued', max_length=20)),
                ('config', models.JSONField()),
                ('cutoff', models.DateTimeField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('forward_start', models.DateTimeField(null=True)),
                ('forward_end', models.DateTimeField(null=True)),
                ('finished_at', models.DateTimeField(null=True)),
                ('artifacts', models.JSONField(default=dict)),
                ('report', models.JSONField(default=dict)),
                ('state', models.JSONField(default=dict)),
                ('last_event_id', models.BigIntegerField(default=0)),
                ('error', models.CharField(blank=True, max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='AutonomyPolicy',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('enabled', models.BooleanField(default=False)),
                ('config', models.JSONField(default=dict)),
                ('next_run_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_cutoff', models.DateTimeField(null=True)),
                ('status', models.CharField(default='Disabled', max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='FuturesCandle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=20)),
                ('opened_at', models.DateTimeField()),
                ('closed_at', models.DateTimeField()),
                ('fetched_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('payload', models.JSONField()),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('symbol', 'opened_at'), name='futures_candle_unique')],
            },
        ),
        migrations.CreateModel(
            name='AutoRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=20)),
                ('kind', models.CharField(max_length=15)),
                ('event_id', models.BigIntegerField()),
                ('at', models.DateTimeField()),
                ('payload', models.JSONField()),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='trading.autocycle')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('cycle', 'symbol', 'kind', 'event_id'), name='auto_record_once')],
            },
        ),
    ]
