# Generated by Django 5.2.17 on 2026-09-11 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0003_autocycle_autonomypolicy_futurescandle_autorecord'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='autorecord',
            name='auto_record_once',
        ),
        migrations.AddField(
            model_name='autorecord',
            name='role',
            field=models.CharField(db_default='selected', default='selected', max_length=12),
        ),
        migrations.AddConstraint(
            model_name='autorecord',
            constraint=models.UniqueConstraint(fields=('cycle', 'symbol', 'role', 'kind', 'event_id'), name='auto_record_once'),
        ),
    ]
